services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - my-web

  my-web:
    build: .
    volumes:
      - .:/var/www/html/
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: '000000' 
      DB_NAME: club_db
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: '000000'
      MYSQL_DATABASE: club_db
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
